### ISSUE TITLE
Could this be used to develop a Chrome Tab Manager?

### ISSUE THREAD

**Issue by philiprhoades** [Mubelotix/wasm-extension-template#2]
I have been interested in looking at Rust for quite a while but haven't actually had a use that would really get me excited enough to jump in.

I use this for managing LOTS of pages and tabs for both Chrome and Brave:

https://github.com/cxw42/TabFern

- the problem is there are some things it can't do and some things where it is very slow - so slow sometimes that it is enough to grind the browser to a halt - and even necessitate a reboot of my Fedora Linux workstation!

So I am thinking this might be an ideal use case and get me started with Rust - what do you think?

Thanks,
Phil.

**Comment by Mubelotix** [comment]
Hi Phil,

This seems very much doable with Rust.
Everything that can be done with JS can be done with Rust thanks to wasm-bindgen.
However, keep in mind that as Wasm is still experimental, it's not guaranteed to have better performance than javascript yet.
I also do not think you will enjoy it that much because APIs are automatically generated by wasm-bindgen which makes them quite ugly sometimes. And you could struggle with error handling since wasm-bindgen errors are quite opaque.
Rust code for wasm isn't as pretty as Rust code should be.
If you are looking for a project to get started, this can do the trick, but you will miss on the beauty and elegance of Rust.

Have fun

**Comment by philiprhoades** [comment]
Wow - thanks for the lightning response!

OK, thanks very much for that feedback - that does put a different complexion on things.

My fallback position is just having a Rust app that can manipulate the existing TabFern LevelDB file to do the heavier things occasionally (after having exited the browser) - I just posted a note asking if anyone has a working app that can do that on the Rust forum.  If I can find an existing working app to just manipulate the data - that would be a convenient work-around - and then after having got started, I could think about this bigger Tab Manager app idea as I get more familiar with Rust . .
